project_name: bkp
release:
  github:
    owner: jojomi
    name: bkp
  name_template: '{{.Tag}}'
  draft: true
builds:
- goos:
  - linux
  # - windows # jojomi/go-script needs to be fixed for windows
  - darwin
  #- freebsd
  #- netbsd
  #- openbsd
  #- dragonfly
  goarch:
  - amd64
  #- "386"
  #- arm
  #- arm64
  goarm:
  - "6"
  - "7"
  main: ./cmd/bkp
  ldflags: -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}
  binary: bkp
  env:
  - CGO_ENABLED=0
archive:
  name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
  format: tar.gz
  format_overrides:
    - goos: windows
      format: zip
  replacements:
    amd64: 64-bit
    386: 32-bit
    darwin: macOS
    openbsd: OpenBSD
    netbsd: NetBSD
    freebsd: FreeBSD
    dragonfly: DragonFlyBSD
    arm: ARM
    arm64: ARM64
  files:
  - licence*
  - LICENCE*
  - license*
  - LICENSE*
  - readme*
  - README*
  - changelog*
  - CHANGELOG*
fpm:
  name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
  bindir: /usr/local/bin
  formats:
    - deb
    #- rpm # needs rpmbuild binary
snapcraft: # sudo python -m pip install pysha3 click requests_unixsocket
  name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
  summary: Backup tool based on restic
  description: Backup tool based on restic
snapshot:
  name_template: SNAPSHOT-{{ .Commit }}
checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_checksums.txt'
dist: dist
